services:
  - type: web
    name: ai-phishing-detector
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PORT
        sync: false
